JuliaStats/TimeSeries.jl

- src/.timeseriesrc.jl
- test/timeseriesrc.jl
> changed defaults to 4 decimals and show int true

- .travis.yml
Update .travis.yml as per #216
> Re-enable Coveralls support (fix #216)

- docs/source/combine.rst
- src/combine.jl
- test/combine.jl
Since #241, improves code quality: more consistent indentation, adding a few tests, and also caring about sorting with time after transformations. 
Do you see anything else that should be worked on for these functionalities? (It was really nice to see new versions for my previous modifications, but I don't personally need those new alterations.)
> Improve code quality for #241

- test/readwrite.jl
- test/timeseriesrc.jl
This allows installing the package elsewhere.
> Use dirname(@__FILE__) instead of Pkg.dir

- NEWS.md
- docs/source/getting_started.rst
- docs/source/timearray.rst
- src/timearray.jl
- test/timearray.jl
closes https://github.com/JuliaStats/TimeSeries.jl/issues/255
> Enforce unique column names

- NEWS.md
- docs/source/combine.rst
- src/combine.jl
- test/combine.jl
- test/meta.jl
> implement more robust merging of meta fields

- .travis.yml
- NEWS.md
- REQUIRE
- src/apply.jl
- src/combine.jl
- src/deprecated.jl
- src/modify.jl
- src/readwrite.jl
- src/split.jl
- src/timearray.jl
- test/apply.jl
- test/combine.jl
- test/modify.jl
- test/split.jl
- test/timearray.jl
- test/timeseriesrc.jl
As noted in this commit message ... ~~DO NOT MERGE~~ ... 
UPDATE: checkbox created in #280  to address remaining problems
> started on changes for julia 0.5

- src/TimeSeries.jl
- src/deprecated.jl
As promised in https://github.com/JuliaStats/TimeSeries.jl/pull/281#discussion_r77683125
> Deprecate using the macro from Base

- src/modify.jl
- test/modify.jl
> Allow update on empty TimeArray

- src/readwrite.jl
- test/readwrite.jl
Closes #297 
IOBuffer for example can be an allowed input
> ENH: readtimearray can accept several kind of input 

- docs/source/index.rst
- docs/source/plotting.rst
> Add plotting doc in index

- NEWS.md
- src/combine.jl
- src/modify.jl
- src/timearray.jl
- test/combine.jl
- test/modify.jl
- test/timearray.jl
> using typed exceptions if possible

- NEWS.md
- docs/source/apply.rst
- src/apply.jl
- src/deprecated.jl
- test/apply.jl
and deprecating the original API
> apply: changing arg order of moving to support do-syntax

- NEWS.md
- docs/source/apply.rst
- src/apply.jl
- src/deprecated.jl
- test/apply.jl
- test/meta.jl
- and deprecating the original API
> apply: changing arg order of `upto` to support do-syntax

- README.md
> update doc badge

- NEWS.md
- README.md
> Update NEWS and README, prepare for releasing

- .travis.yml
- README.md
~will update badge on README later~ done
> ci: switch to Codecov

- src/TimeSeries.jl
- src/split.jl
- test/modify.jl
- test/split.jl
Added `first` and `last` methods. `head` and `tail` now defaults to `n = 6`.
> Added first and last (#294)

- .travis.yml
- docs/Project.toml
- docs/REQUIRE
ref: https://juliadocs.github.io/Documenter.jl/latest/man/hosting/#.travis.yml-Configuration-1
> fix documentation auto deployment

- NEWS.md
- src/modify.jl
- src/timearray.jl
- test/timearray.jl
e.g.
```julia
julia> meta(cl)
"AAPL"
julia> cl′ = TimeArray(cl; meta = :AAPL);
julia> meta(cl′)
:AAPL
```
TODO
> timearray: new constructor for creating from existing `TimeArray`

- src/timearray.jl
- test/timearray.jl
> Construct TimeArray with NamedTuple

- src/apply.jl
- src/utilities.jl
Raise a more specific ArgumentError when an unsupported method is given to dropnan().
> Be specific about exception type.

- .editorconfig
> introduce EditorConfig

- NEWS.md
- docs/src/combine.md
- src/apply.jl
- src/combine.jl
- src/deprecated.jl
- test/combine.jl
- test/meta.jl
```julia
merge(ta1, ta2, ta3)
```
close #410
TODO
> combine: `merge` Vararg support

- NEWS.md
- docs/src/modify.md
- src/TimeSeries.jl
- src/combine.jl
- src/modify.jl
- src/utilities.jl
- test/modify.jl
> modify: implement rename! method

- src/combine.jl
- test/combine.jl
> Fix parameter `colnames` of `merge`

- Project.toml
This is done to match the release new version
> Change `Reexport` compatibility requirement

- .github/workflows/DocCleanup.yml
ref: https://juliadocs.github.io/Documenter.jl/v0.26/man/hosting/#gh-pages-Branch
> Add DocCleanup.yml

- src/plotrecipes.jl
> Fix plots recipes

- src/combine.jl
- test/combine.jl
- improve memory consumption and performance
- type promotion
close #498
> combine: support `Period` for collapse

- docs/src/combine.md
> doc/collapse: add `Dates.quarter` in the list

- src/timearray.jl
Update docstring as it's incorrect and confuses me
> Update TimeArray Named Tuple docstring
