src/TimeSeries.jl
src/combine.jl
test/combine.jl

The new `merge1` (designed to replace the current `merge`) has about a quarter of the lines of code (40 -> 10) and runs faster.
````julia
julia> @elapsed merge(AAPL,BA)
0.608618657
julia> @elapsed merge(AAPL,BA)
0.465285163
julia> @elapsed merge(AAPL,BA)
0.471265437
julia> @elapsed merge1(AAPL,BA)
0.121858314
julia> @elapsed merge1(AAPL,BA)
0.106935782
julia> @elapsed merge1(AAPL,BA)
0.116042072
````
That's about 4-5x speed improvement!

adding faster merge1

---

src/apply.jl
test/apply.jl
test/combine.jl
test/meta.jl
test/readwrite.jl
test/split.jl
test/timearray.jl
test/timeseriesrc.jl

Explicitly import math/inequality operators from Base to remove new 0.4 warnings like:
`WARNING: module TimeSeries should explicitly import .+ from Base`
A few tests had also started failing due a lack of agreeing significant digits with the FactCheck `roughly` function, e.g.
```
Failure :: (line:-1) :: correct alignment and operation between two TimeVectors :: fact was false
Expression: cl .* op.values[1] --> roughly(11740.27)
Expected: 11740.267199999998 ≅ 11740.27
```
so I increased the precision of the expected results.

Fix deprecation warnings

---

NEWS.md
REQUIRE
docs/source/operators.rst
src/apply.jl
src/split.jl
src/timearray.jl
test/apply.jl

A master-compatible version of https://github.com/JuliaStats/TimeSeries.jl/pull/197 - switches the value container from `Array` to `AbstractArray` and implements `!`, `~`, `&`, `|`, `$`, `%`, `!==`, and unary `+` and `-`, with appropriate documentation.

Switch to AbstractArrays and refactor / generalize operator code

---

src/timearray.jl
test/timearray.jl

Also adds tests for `show`ing various lengths of TimeArray.
Example:
```julia
julia> using MarketData
julia> ohlc[1:0]
0x4 TimeSeries.TimeArray{Float64,2,Void}
Open   High   Low    Close  
```

Fix BoundsError when calling show on empty TimeArray

---

src/apply.jl
test/apply.jl

Unary operator definitions are essentially identical to calling `basecall` with a particular function, so predefine common scalar->scalar math functions as unary operators for convenience.
Example:
```julia
julia> sqrt(ohlc)
500x4 TimeSeries.TimeArray{Float64,2,Void} 2000-01-03 to 2001-12-31
sqrtOpen  sqrtHigh  sqrtLow  sqrtClose  
2000-01-03 | 10.2411   10.6066   10.0841  10.5802    
2000-01-04 | 10.4043   10.5176   10.0593  10.1242    
2000-01-05 | 10.1858   10.5148   10.1489  10.198     
2000-01-06 | 10.3015   10.3441   9.7468   9.7468     
⋮
2001-12-26 | 4.6206    4.7223    4.5978   4.6357     
2001-12-27 | 4.6454    4.717     4.6454   4.6979     
2001-12-28 | 4.6872    4.7958    4.6861   4.736      
2001-12-31 | 4.7445    4.7603    4.6723   4.6797     
```

Add common scalar->scalar math functions as unary operators

---

NEWS.md
docs/source/getting_started.rst
src/apply.jl
test/apply.jl

Before:
```julia
julia> using MarketData
julia> cl .* (cl .> 100)
ERROR: MethodError: `.*` has no method matching .*(::TimeSeries.TimeArray{Float64,1,Date,Array{Float64,1}}, ::TimeSeries.TimeArray{Bool,1,Date,BitArray{1}})
Closest candidates are:
.*{T<:Number,N}(::TimeSeries.TimeArray{T<:Number,N,D<:Base.Dates.TimeType,A<:AbstractArray{T,N}}, ::Number)
.*{T<:Number,N}(::Number, ::TimeSeries.TimeArray{T<:Number,N,D<:Base.Dates.TimeType,A<:AbstractArray{T,N}})
.*{T<:Number,N,M}(::TimeSeries.TimeArray{T<:Number,N,D<:Base.Dates.TimeType,A<:AbstractArray{T,N}}, ::TimeSeries.TimeArray{T<:Number,M,D<:Base.Dates.TimeType,A<:AbstractArray{T,N}})
```
After:
```julia
julia> using MarketData
julia> cl .* (cl .> 100)
500x1 TimeSeries.TimeArray{Float64,1,Date,Array{Float64,1}} 2000-01-03 to 2001-12-31 …
```

Support element-wise math across heterogeneous Number subtypes - fix #224

---

NEWS.md
src/readwrite.jl

Fixes an issue where column headings might not be automatically interpreted as strings during file loading (for example, if column names are numbers).

Explicitly convert column headings to strings in readtimearray

---

NEWS.md
src/apply.jl
src/combine.jl
src/readwrite.jl
test/meta.jl

Added default (`Void`) metadata to merge and math operation results when input metas don't match. Also allows for meta to be set explicitly during merge.

Allow operations on TimeArrays with non-matching meta - address #249

---

docs/source/combine.rst
src/combine.jl
src/deprecated.jl
test/combine.jl
test/deprecated.jl
test/meta.jl

Fixes #243 to allow `collapse` operations on 2D TimeArrays, with appropriate tests. Scores a nice speedup as well:
`master`:
```julia
julia> using TimeSeries, MarketData
julia> collapse(BA["Open"], last); @time collapse(BA["Open"], last);
0.188057 seconds (294.44 k allocations: 46.848 MB, 2.21% gc time)
```
this PR:
```julia
julia> using TimeSeries, MarketData
julia> collapse(BA["Open"], last); @time collapse(BA["Open"], last);
0.026178 seconds (118.08 k allocations: 33.954 MB, 12.61% gc time)
```
While we're looking at this, should there be an option for what timestamp is used to represent the downsampled rows? The current approach is to use the last timestamp in the cluster, although I think using the first timestamp would be just as justifiable (in fact preferable for my typical use …

Multi-column collapse

---

src/TimeSeries.jl

This pulls in the exports outside of the package whenever anyone uses it, rather than just inside the package's module.

Don't do using Dates outside the top package module

---

src/split.jl
test/split.jl

Useful when the time series is empty (e.g. due to a previous filtering with `to` or `from`).

More robust to() and from()

---

REQUIRE
src/TimeSeries.jl
src/plotrecipes.jl

This adds basic plotting functionality to TimeArray objects, with a very light dependency (RecipesBase a single macro). It allows plotting as simply as `plot(ohlc)`.
Discussed here https://github.com/JuliaPlots/StatPlots.jl/issues/37#issuecomment-278708392 and here https://github.com/JuliaStats/TimeSeries.jl/issues/302 .
The current recipe will plot all values in the array, which may not make sense if they are not on the same scale, but you can always `plot(ohlcv["Volume"])`.

added basic plot recipe

---

src/plotrecipes.jl

I implemented support for candlestick and Heikin-Ashi candlestick plots for OHLC data using the links given by @milktrader here: https://github.com/JuliaPlots/StatPlots.jl/issues/37
OHLC appears to constitute quite a lot of the data currently associated with TimeSeries.
The recipe looks in the colnames for “open” “low” “high” and “close” (ignoring case) and throws an error if it does not find them. There are possibly better ways of doing this but this code (the extract_ohlc function) is straightforward to adapt.
I thought this would take me an hour but turned out I was really wrong :-)
I think it is best if the documentation is adapted by one of you who work with this data type. It should be straightforward from the examples given below.

Candlesticks

---

src/plotrecipes.jl

In some cases `plot` would complain about the seriestype not changing.

Change seriestype in recipe

---

src/timearray.jl
test/timearray.jl

allows TimeArrays to be constructed from view_s of another TimeArray's timestamps
just as TimeArrays can be constructed from view_s of another TimeArray's values

allow views of timestamps in constructors

---

NEWS.md
src/combine.jl
test/combine.jl

For simple use case, it's faster than `merge`.
(`merge` serves as inner / outer join, which differs from `hcat`)
```julia
julia> @benchmark merge($cl, $ohlc)
BenchmarkTools.Trial:
memory estimate:  210.75 KiB
allocs estimate:  5122
--------------
minimum time:     273.470 μs (0.00% GC)
median time:      279.141 μs (0.00% GC)
mean time:        299.841 μs (5.72% GC)
maximum time:     2.998 ms (79.71% GC)
--------------
samples:          10000
evals/sample:     1
julia> @benchmark [$cl $ohlc]
BenchmarkTools.Trial:
memory estimate:  58.14 KiB
allocs estimate:  1360
--------------
minimum time:     77.604 μs (0.00% GC)
median time:      80.881 μs (0.00% GC)
mean time:        102.880 μs (6.02% GC)
maximum time:     5.132 ms (90.05% GC)
--------------
samples:          10000
evals/sample:     1 …
```

combine: `hcat` support

---

NEWS.md
src/basemisc.jl
test/basemisc.jl

- sum
- mean
- std
- var
- cumprod

timearray: more Base functions support

---

README.md

The current link in the main text points to a page with just a stub.

Wrong link to doc

---

docs/src/apply.md
src/apply.jl
test/apply.jl

This pull request adds a new parameter `differences` to the `diff` function, to calculate higher order differences. The default value is `1`, so this change is backwards compatible.

Higher order differences for diff function

---

src/timearray.jl
test/timearray.jl

The copy base function is necessary to use the [Bootstrap package](https://github.com/juliangehring/Bootstrap.jl).
The Bootstrap package will also need some changes, but this paves the way to being able to use both packages together.

Add copy function to TimeArray

---

src/deprecated.jl

In the deprecation warning, the message suggests to change operators such as `==` by `==.` (trailing dot), when the actual operator is `.==` (leading dot).
This pull request reports the correct names for those operators.

Some alternatives to deprecated operators are wrongly displayed

---

NEWS.md
src/deprecated.jl
src/timearray.jl
test/timearray.jl

```julia
julia> cl == copy(cl)
true
```
---
@dourouc05 please review this

timearray: Revoke deprecation of `==` and redefine its meaning

---

src/timearray.jl
test/timearray.jl

I've been trying to use ```TimeSeries.jl``` on some high frequency datasets and ran into some performance bottlenecks in ```TimeArray``` construction. In particular the uniqueness test is heavy.
I've made a couple of changes here that help my use cases:
* Check sorted and uniqueness in one pass, allocation free.
* Add option to disable construction checks entirely.
Rough performance improvements for something on the scale of my use case, 10 million entries, 1 column:
* Previous: ~4 seconds
* New: ~8ms
* New unchecked: ~20us
If these changes look reasonable I have a few more I'd like to add. To extend this I'd change some of the algorithms to construct ```TimeArray``` objects unchecked. I also noticed a few places that don't handle ```Float32``` properly, and I'd like to rectify that.

Construct opt

---

NEWS.md
src/apply.jl
test/apply.jl

```julia
julia> diff(cl, 5)
495x1 TimeSeries.TimeArray{Float64,1,Date,Array{Float64,1}} 2000-01-10 to 2001-12-31
│            │ Close  │
├────────────┼────────┤
│ 2000-01-10 │ -14.19 │
│ 2000-01-11 │ -9.75  │
│ 2000-01-12 │ -16.81 │
⋮
│ 2001-12-27 │ 0.45   │
│ 2001-12-28 │ 1.76   │
│ 2001-12-31 │ 0.9    │
```

apply: make `diff` support `n` time steps lag

---

src/combine.jl
src/timearray.jl
src/utilities.jl
test/combine.jl

Summary:
* Unchecked construction of TimeArray objects.
* Direct implementation of outer join.
* Support for arbitrary types by user defined missing value.
* More optimal index based assignment than generic indexing operation (applies to left, right, and outer join).
Mostly focused on optimizing outer join. Benchmark example:
```Julia
using TimeSeries
using BenchmarkTools
struct SimpleTime <: Dates.TimeType
value::Int64
end
Base.isless(x::SimpleTime, y::SimpleTime) = x.value < y.value
Base.isequal(x::SimpleTime, y::SimpleTime) = x.value == y.value
Base.:(==)(x::SimpleTime, y::SimpleTime) = x.value == y.value
t1 = [SimpleTime(x) for x in 1:2_000_000]
t2 = [SimpleTime(2 * x) for x in 1:2_000_000]
v1 = rand(Float64, length(t1), 10)
v2 = rand(Float64, length(t2), 10)
ts1 = TimeArray(t1, v1) …
```

merge() optimization

---

docs/src/indexing.md

There was a correction needed in  indexing.md.

Correction in the Row Indexing, Integer table

---

src/combine.jl
test/combine.jl

This allows collapse to be used with types for which adjoint is not defined, such as strings.
It also prevents complex numbers from being conjugated, which may have come as a surprise to users.

Swap adjoint for permutedims in collapse

---

src/timearray.jl
test/timearray.jl

Now a one-line short version will be output (when no MIME type is specified). The previous long version will be output for ::MIME"text/plain", e.g., when printing in the REPL. The tests were also updated.
The motivation for this change comes from including timearray objects in structs and dicts. Printing of the parent object resulted in the full printing of the timearray instead of a summary statement. This PR enables the printing of just a summary statement in such a case.

Revise show method for timearray

---

src/plotrecipes.jl

This is a workaround for a bug in Plots.pgfplots() which prevents labels::Symbol to be shown.
see JuliaPlots/Plots.jl#2020

Plotting: labels as strings

---

src/readwrite.jl
test/readwrite.jl

To make writetimearray() symmetric with readtimearray().

 Support delimiter, header and format when writing time series

---

NEWS.md
src/apply.jl
test/apply.jl

* introduce `SubArray` to remove allocations.
* Case of single column `TimeArray`:
Before
```julia
julia> @benchmark moving(mean, cl, 20)
BenchmarkTools.Trial:
memory estimate:  125.06 KiB
allocs estimate:  489
--------------
minimum time:     34.383 μs (0.00% GC)
median time:      44.607 μs (0.00% GC)
mean time:        58.768 μs (14.77% GC)
maximum time:     46.406 ms (99.84% GC)
--------------
samples:          10000
evals/sample:     1
```
After
```julia
julia> @benchmark moving(mean, cl, 20)
BenchmarkTools.Trial:
memory estimate:  31.05 KiB
allocs estimate:  491
--------------
minimum time:     12.639 μs (0.00% GC)
median time:      13.740 μs (0.00% GC)
mean time:        24.643 μs (37.05% GC)
maximum time:     57.679 ms (99.95% GC)
--------------
samples:          10000
evals/sample: …
```

apply: improve performance of `moving`

---

NEWS.md
docs/src/apply.md
src/apply.jl
test/apply.jl

Ref: #401 
TODO
e.g.
```julia
julia> moving(ohlc, 5, dims = 2, colnames = [:μ]) do A
mean(A, dims = 1)
end
496×1 TimeArray{Float64,1,Date,Array{Float64,1}} 2000-01-07 to 2001-12-31
│            │ μ        │
├────────────┼──────────┤
│ 2000-01-07 │ 98.125   │
│ 2000-01-10 │ 99.1875  │
│ 2000-01-11 │ 94.6425  │
│ 2000-01-12 │ 91.0475  │
│ 2000-01-13 │ 95.62    │
│ 2000-01-14 │ 100.5175 │
│ 2000-01-18 │ 102.845  │
│ 2000-01-19 │ 106.0775 │
│ 2000-01-20 │ 116.0    │
│ 2000-01-21 │ 112.5    │
│ 2000-01-24 │ 108.14   │
│ 2000-01-25 │ 108.1875 │
│ 2000-01-26 │ 111.0325 │
│ 2000-01-27 │ 109.7025 │
```

apply: `moving` with multi-column

---

NEWS.md
src/timearray.jl
test/timearray.jl

close #420
```julia
julia> cl[]
ERROR: BoundsError: attempt to access TimeArray{Float64,1,Date,Array{Float64,1}}
at index []
```

timearray: `getindex(ta)` throws BoundsError

---

NEWS.md
docs/src/indexing.md
src/timearray.jl
test/timearray.jl

close #411
```julia
ohlc[1:42,   [:High, :Low]]
ohlc[42:end, [:High, :Low]]
ohlc[:,      [:High, :Low]]
ohlc[42,     [:High, :Low]]
```
---
TODO

timearray: add simple 2D getindex support

---

NEWS.md
src/timearray.jl

E.g.
```julia
julia> f(ta) = @inbounds ta[1000]
f (generic function with 1 method)
julia> f(cl)
1×1 TimeArray{Float64,1,Date,Array{Float64,1}} 40636496360509-30141738682531949-3689348814741910343 to 40636496360509-30141738682531949-3689348814741910343
│                                                      │ Close │
├──────────────────────────────────────────────────────┼───────┤
│ 40636496360509-30141738682531949-3689348814741910343 │ 0.0   │
```

timearray: fix `inbounds` handling

---

src/plotrecipes.jl

Fixes #430, works with multiple labels.

Fixed labels bug in plotrecipes.jl

---

NEWS.md
docs/src/plotting.md
src/plotrecipes.jl
test/plotrecipes.jl
test/runtests.jl

The function find is not defined and caused an UndefVarError
when this line was executed.
Fixes #432

Replace find -> findall and fix issue 432

---

Project.toml

Should be 100% safe. Might we get a release with this please? This is one of the packages holding back upgrading RecipesBase (and by extension Plots).

recipesbase compat

---

src/tables.jl
src/timearray.jl
test/tables.jl

- `TimeArray(table; ..., timeparser::Callable)`
e.g.
```julia
using Dates
TimeArray(CSV.File("..."), timestamp = :date, timeparser = Date ∘ unix2datetime)
```
close #442

TimeArray: add a new kw args for Tables constructor

---

src/readwrite.jl

By creating a DataFormat only once, the performance of parsing custom date and datetime formats is speed up a lot (this is also inline with Julia recommendations). 
In my own tests the time spent reading several CSV files went from over 400 seconds to just 8 seconds (intraday stock quotes), so 50x improvement.

Large performance improvement when parsing custom date formats

---

docs/src/split.md
src/split.jl
test/split.jl

```julia
julia> @benchmark findall($cl .> 100)
BenchmarkTools.Trial:
memory estimate:  10.53 KiB
allocs estimate:  28
--------------
minimum time:     6.108 μs (0.00% GC)
median time:      7.105 μs (0.00% GC)
mean time:        8.535 μs (9.45% GC)
maximum time:     2.347 ms (98.30% GC)
--------------
samples:          10000
evals/sample:     5
julia> @benchmark findall(>(100), $cl)
BenchmarkTools.Trial:
memory estimate:  2.28 KiB
allocs estimate:  8
--------------
minimum time:     2.064 μs (0.00% GC)
median time:      2.974 μs (0.00% GC)
mean time:        3.067 μs (2.51% GC)
maximum time:     201.347 μs (97.47% GC)
--------------
samples:          10000
evals/sample:     9
```
Ref https://github.com/JuliaStats/TimeSeries.jl/issues/456#issuecomment-800083464

findall: support custom function as argument

---

docs/src/combine.md
src/TimeSeries.jl
src/combine.jl
test/combine.jl

Ref #498. 
This PR is the first part for fixing #498.
The following works are
1. Add a new signature of collapse to accept `Period` type.
2. Handling type promotion like `map` does.
@clouds56 Could you try this PR out?

combine: fix `collapse` period calculation for Dates accessors methods

---

src/plotrecipes.jl

The current recipe produces a separate label for each bar, which completely clutters the plot if a user calls `plot(ta; legend = :topleft)` (or any other legend position). With this change no labels are produced by default, allowing the user to combine the candlestick plot with other plots and add a legend without having dozens of `y1, y2, y3`... entries in the legend.

Remove candletick series labels
